---
- name: Execute kubeadm command
  become: true
  ansible.builtin.command:
    cmd: |
      kubeadm {{ kubeadm_action }}
      {% if kubeadm_phase is defined %}
      {{ kubeadm_phase }}
      {% endif %}
      {% if kubeadm_component is defined %}
      {{ kubeadm_component }}
      {% endif %}
      {% if kubeadm_subcomponent is defined %}
      {{ kubeadm_subcomponent }}
      {% endif %}
      {% if kubeadm_use_config_file %}
      --config {{ kubeadm_config_file }}
      {% endif %}
  changed_when: false
