---
- name: Validate prerequis
  ansible.builtin.include_tasks: requirements.yml

- name: Setup machines
  ansible.builtin.include_tasks: "prepare/{{ ansible_os_family | lower }}.yml"

- name: Setup network
  ansible.builtin.include_tasks: prepare/network.yml

- name: Configuration file
  ansible.builtin.include_tasks: configuration-file.yml
  when: kubeadm_use_config_file

- name: Initialize control plane node
  when: "'control_planes' in group_names"
  ansible.builtin.include_tasks: control-plane.yml
