---
# - name: Validate prerequis
#   ansible.builtin.include_tasks: requirements.yml

# - name: Setup machines
#   ansible.builtin.include_tasks: "prepare/{{ ansible_os_family | lower }}.yml"

# - name: Setup network
#   ansible.builtin.include_tasks: prepare/network.yml

# - name: Initialize control plane node
#   when: "'control_planes' in group_names"
#   ansible.builtin.include_tasks: control-plane.yml

- name: CA hash key
  ansible.builtin.include_tasks: ca-hash-key.yml
  when: "inventory_hostname == groups['control_planes'][0]"

- name: Join nodes to the cluster
  when: "'worker_nodes' in group_names"
  ansible.builtin.include_tasks: worker-node.yml
