---
- name: Validate prerequis
  ansible.builtin.include_tasks: prepare/requirements.yml

- name: Setup machines
  ansible.builtin.include_tasks: "prepare/{{ ansible_os_family | lower }}.yml"

- name: Setup network
  ansible.builtin.include_tasks: prepare/network.yml

- name: Initialize control plane node
  when: "'control_planes' in group_names"
  ansible.builtin.include_tasks: setup/control_plane.yml

- name: Prepare worker node to join the cluster
  ansible.builtin.include_tasks: setup/prepare_worker_join.yml
  when: "inventory_hostname == groups['control_planes'][0]"

- name: Join nodes to the cluster
  when: "'worker_nodes' in group_names"
  ansible.builtin.include_tasks: setup/worker_node.yml
