---
- name: Configuration file
  ansible.builtin.include_tasks: setup/configuration_file.yml

- name: Worker node join
  ansible.builtin.include_tasks: join/worker_join.yml

- name: Ensure worker nodes are Ready
  ansible.builtin.include_tasks: check/readiness.yml
  vars:
    kubeadm_node: "{{ ansible_hostname }}"
