---
- name: Get canal manifest file
  ansible.builtin.get_url:
    url: "{{ kubeadm_cni_canal_manifest }}"
    dest: "/tmp/{{ kubeadm_cni_name }}.yaml"
    mode: '0644'

- name: Get canal manifest file content
  ansible.builtin.slurp:
    src: "/tmp/{{ kubeadm_cni_name }}.yaml"
  register: kubeadm_cni_canal

- name: Deploy canal in the cluster
  ansible.builtin.command:
    cmd: "kubecl create -f /tmp/{{ kubeadm_cni_name }}.yaml --kubeconfig={{ kubeadm_admin_conf_file }}"
  register: kubeadm_deploy_canal
  changed_when: '"created" in kubeadm_deploy_canal.stdout_lines'
  failed_when: false
