---
- name: Kubeadm create all static Pod manifest files necessary to establish the control plane
  become: true
  block:
    - name: Kubeadm make a dry-run to compare changes
      become: true
      ansible.builtin.command:
        cmd: "kubeadm join --config {{ kubeadm_config_file }} --dry-run"
      register: kubeadm_kubelet_dry_run
      changed_when: false
    - name: Generate control plane manifests files
      ansible.builtin.copy:
        src: "{{ kubeadm_kubelet_dry_run | regex_search('/etc/kubernetes/tmp/kubeadm-init-dryrun([0-9]+)') }}/{{ item }}"
        dest: "/var/lib/kubelet/{{ item }}"
        mode: '0644'
        remote_src: true
      loop: "{{ kubeadm_kubelet_files }}"
      notify: Restart kubelet

- name: Restart kubelet now
  ansible.builtin.meta: flush_handlers

- name: Waiting for kubelet being ready
  ansible.builtin.wait_for:
    timeout: 45
