---
# FIXME: tasks must be indempotent

- name: Install required addons for passing conformance tests
  become: true
  ansible.builtin.command:
    cmd: "kubeadm init phase addon all --config {{ kubeadm_config_file }}"
  register: result
  changed_when: false
