---
# FIXME: tasks must be indempotent
- name: Generate static Pod manifest file for local etcd
  become: true
  ansible.builtin.command:
    cmd: "kubeadm init phase etcd local --config {{ kubeadm_config_file }}"
  register: result
  changed_when: '"Writing" in result.stdout'
