---
# FIXME: tasks must be indempotent

- name: Updates settings relevant to the kubelet after TLS bootstrap
  become: true
  ansible.builtin.command:
    cmd: "kubeadm init phase kubelet-finalize all --config {{ kubeadm_config_file }}"
  register: result
  changed_when: false
