---
- name: Generate all kubeconfig files necessary to establish the control plane and the admin kubeconfig file
  become: true
  ansible.builtin.command:
    cmd: "kubeadm init phase kubeconfig all"
  register: result
  changed_when: '"Writing" in result.stdout'
