---
# FIXME: tasks must be indempotent

- name: Upload all configuration to a ConfigMap
  become: true
  ansible.builtin.command:
    cmd: "kubeadm init phase upload-config all --config {{ kubeadm_config_file }}"
  register: result
  changed_when: false
