---
- name: Gathering informations about ConfigMaps
  become: true
  ansible.builtin.command:
    cmd: "kubectl get configmap -n kube-system --kubeconfig={{ kubeadm_admin_conf_file }} -o custom-columns=NAME:.metadata.name"
  changed_when: false
  register: kubeadm_configmaps

- name: Upload all configuration to a ConfigMap
  become: true
  ansible.builtin.command:
    cmd: "kubeadm init phase upload-config all --config {{ kubeadm_config_file }}"
  register: result
  changed_when: (kubeadm_configmaps.stdout.split() | intersect(kubeadm_init_configmaps)) | length < kubeadm_init_configmaps | length
